//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsForm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudentsForm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _38bk2udqspkggdn6dsrg2d1bos {
            get {
                object obj = ResourceManager.GetObject("38bk2udqspkggdn6dsrg2d1bos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _76956973_2553233311576102_2105318425046810624_n {
            get {
                object obj = ResourceManager.GetObject("76956973_2553233311576102_2105318425046810624_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _CITYPNG_COM_Transparent_HD_Red___Purple_Neon_Frame_Button___5046x1920 {
            get {
                object obj = ResourceManager.GetObject("[CITYPNG.COM]Transparent HD Red & Purple Neon Frame Button - 5046x1920", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap compar_100 {
            get {
                object obj = ResourceManager.GetObject("compar_100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Daco_4810872__1_ {
            get {
                object obj = ResourceManager.GetObject("Daco_4810872 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_button_euclidean_vector_download_classic_share_button_creative_5a6c456ced4dc6_402646561517045100972 {
            get {
                object obj = ResourceManager.GetObject("kisspng-button-euclidean-vector-download-classic-share-button-creative-5a6c456ced" +
                        "4dc6.402646561517045100972", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_button_euclidean_vector_download_classic_share_button_creative_5a6c456ced4dc61 {
            get {
                object obj = ResourceManager.GetObject("kisspng-button-euclidean-vector-download-classic-share-button-creative-5a6c456ced" +
                        "4dc61", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_c_programming_basics_for_absolute_beginners_comp_5b1061268e45a8_2307225915278001025828 {
            get {
                object obj = ResourceManager.GetObject("kisspng-c-programming-basics-for-absolute-beginners-comp-5b1061268e45a8.230722591" +
                        "5278001025828", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_icon_design_portable_network_graphi_login_akun_fwd_life_indonesia_5baa70084d9ef6_7432866515378964563179 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-icon-design-portable-network-graphi-login-akun-fwd-life-in" +
                        "donesia-5baa70084d9ef6.7432866515378964563179", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_identity_document_id_card_5ac242cb7d9eb8_2823795215226805235145 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-identity-document-id-card-5ac242cb7d9eb8.28237952152268052" +
                        "35145", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PikPng_com_clean_icon_png_4296879 {
            get {
                object obj = ResourceManager.GetObject("PikPng.com_clean-icon-png_4296879", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PikPng1 {
            get {
                object obj = ResourceManager.GetObject("PikPng1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PikPng2 {
            get {
                object obj = ResourceManager.GetObject("PikPng2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PinClipart_com_network_clipart_1330450 {
            get {
                object obj = ResourceManager.GetObject("PinClipart.com_network-clipart_1330450", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngfind_com_slash_mark_png_792968 {
            get {
                object obj = ResourceManager.GetObject("pngfind.com-slash-mark-png-792968", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PngItem_1280822 {
            get {
                object obj = ResourceManager.GetObject("PngItem_1280822", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngkey_com_graduation_png_images_4003680 {
            get {
                object obj = ResourceManager.GetObject("pngkey.com-graduation-png-images-4003680", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap show_password_icon_17 {
            get {
                object obj = ResourceManager.GetObject("show-password-icon-17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap show_password_icon_17__1_ {
            get {
                object obj = ResourceManager.GetObject("show-password-icon-17 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap show_password_icon_17__2_ {
            get {
                object obj = ResourceManager.GetObject("show-password-icon-17 (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap show_password_icon_18 {
            get {
                object obj = ResourceManager.GetObject("show-password-icon-18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap show_password_icon_18__1_ {
            get {
                object obj = ResourceManager.GetObject("show-password-icon-18 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap show_password_icon_19 {
            get {
                object obj = ResourceManager.GetObject("show-password-icon-19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap teacher {
            get {
                object obj = ResourceManager.GetObject("teacher", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap transparent_refresh_icon_5db01c6eaf9925_0856390815718227027193 {
            get {
                object obj = ResourceManager.GetObject("transparent-refresh-icon-5db01c6eaf9925.0856390815718227027193", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Web_Developer {
            get {
                object obj = ResourceManager.GetObject("Web-Developer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap white_plus_plus_icon_white_texture_white_board_clothing_apparel_transparent_png_425162 {
            get {
                object obj = ResourceManager.GetObject("white-plus-plus-icon-white-texture-white-board-clothing-apparel-transparent-png-4" +
                        "25162", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap white_plus_plus_icon_white_texture_white_board_clothing_apparel_transparent_png_4251621 {
            get {
                object obj = ResourceManager.GetObject("white-plus-plus-icon-white-texture-white-board-clothing-apparel-transparent-png-4" +
                        "251621", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap white_plus_plus_icon_white_texture_white_board_clothing_apparel_transparent_png_4251622 {
            get {
                object obj = ResourceManager.GetObject("white-plus-plus-icon-white-texture-white-board-clothing-apparel-transparent-png-4" +
                        "251622", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
